service: starter-dev-backend
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-bundle
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000

provider:
  name: aws
  profile: starterdev
  stage: dev
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
